### ISSUE TITLE
Account Credentials

### ISSUE THREAD

**Issue by Yakito** [RantirAI/rantir-cloud-go#32]
So, it looks like the credentials we have are not working, can we add to this thread correct credentials for:
- regular user
- admin user

Thanks!
[Slack Message](https://computir-ai.slack.com/archives/C06UDDNFVGE/p1724975685172689)

**Comment by brianmusuku** [comment]
all users need to be admin or ai-explore will not work @Yakito

**Comment by farreledwin** [comment]
Yes, you can try that on turner.rantir.app @Yakito
